
export const SliderData = [
  {
    slug: "/product-details",
    img: "/img/products/2.png",
    title: "პროდუქტის ",
    price: "17.5",
    sale: false,
    new: true,
  },
  {
    slug: "/product-details",
    img: "/img/products/3.png",
    title: "პროდუქტის ",
    price: "17.5",
    sale: true,
    new: false,
  },
  {
    slug: "/product-details",
    img: "/img/products/4.png",
    title: "პროდუქტის ",
    price: "17.5",
    sale: false,
    new: false,
  },
  {
    slug: "/product-details",
    img: "/img/products/5.png",
    title: "პროდუქტის ",
    price: "17.5",
    sale: true,
    new: false,
  },
  {
    slug: "/product-details",
    img: "/img/products/6.png",
    title: "პროდუქტის ",
    price: "17.5",
    sale: false,
    new: false,
  },
  {
    slug: "/product-details",
    img: "/img/products/7.png",
    title: "პროდუქტის ",
    price: "17.5",
    sale: false,
    new: true,
  },
  {
    slug: "/product-details",
    img: "/img/products/1.png",
    title: "პროდუქტის ",
    price: "17.5",
    sale: false,
    new: false,
  },
];
